---
definitions:
  steps:
    - step: &Install-dependencies
        caches:
          - node
        name: Install dependencies
        script:
          - yarn --frozen-lockfile
    - step: &Check
        caches:
          - node
        name: Check
        script:
          - "yarn lint"
          # - "yarn audit"
          - "yarn test:unit"
image: "node:latest"
pipelines:
  branches:
    master:
      - step: *Install-dependencies
      - step: *Check
      - step:
          artifacts:
            - tableau-view.tar.gz
          caches:
            - node
          name: Build
          script:
            # - yarn build
            - tar --exclude="./node_modules" --exclude="./.git" -czvf tableau-view.tar.gz . 
      - step:
          deployment: production
          name: Deploy
          script:
            - pipe: "atlassian/heroku-deploy:1.1.3"
              variables:
                DEBUG: "true"
                HEROKU_API_KEY: $HEROKU_APP_KEY
                HEROKU_APP_NAME: $HEROKU_APP_NAME
                ZIP_FILE: tableau-view.tar.gz
  default:
    - step: *Install-dependencies
    - step: *Check